package com.diy.e_commerce_app.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a cart item in the e-commerce application.
 * Each cart item is associated with a product and contains the quantity of the product added to the cart.
 */
@Entity
@Table(name = "cart_items")
@Data
@NoArgsConstructor
public class CartItem {

    /**
     * Unique identifier for the cart item.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The product associated with this cart item.
     * This represents a many-to-one relationship between cart items and products.
     * Each cart item refers to one product.
     */
    @NotNull
    @ManyToOne
    @JoinColumn(name = "product_id") // Specifies the foreign key column in the database.
    private Product product;

    /**
     * The quantity of the product added to the cart.
     * This value must not be null.
     */
    @NotNull
    private Integer quantity;
}
